name: test_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjusted for broader compatibility

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1

  # State Management
  flutter_riverpod: ^2.5.1

  # UI Packages
  cupertino_icons: ^1.0.8
  table_calendar: ^3.1.2
  fl_chart: ^1.0.0
  vibration: ^3.1.3

  # Data Modeling & Utilities
  freezed_annotation: ^2.4.1 # Downgraded for compatibility
  json_annotation: ^4.9.0
  collection: ^1.18.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Quality
  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.4.11
  freezed: ^2.5.2 # Downgraded for compatibility
  json_serializable: ^6.8.0
  mocktail: ^1.0.0
  firebase_auth_mocks: ^0.15.0
  fake_cloud_firestore: ^4.0.0
  mockito: ^5.0.0

flutter:
  uses-material-design: true