// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8l6Y7XnzTyNOs6S3OpsJ1DuAIa_2p7lg',
    appId: '1:1019816135958:web:029381955d1d601759d437',
    messagingSenderId: '1019816135958',
    projectId: 'tgwapp-75d8b',
    authDomain: 'tgwapp-75d8b.firebaseapp.com',
    storageBucket: 'tgwapp-75d8b.firebasestorage.app',
    measurementId: 'G-YGP2TC828B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcSQY-_Kv6Qoy0ki1cyccP3e_8XmFDIHs',
    appId: '1:1019816135958:android:1beb4278b750cd4e59d437',
    messagingSenderId: '1019816135958',
    projectId: 'tgwapp-75d8b',
    storageBucket: 'tgwapp-75d8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-OYkuS2RDiQuPGFXrcvIWIRuT4qkMbv8',
    appId: '1:1019816135958:ios:14d015525926a25f59d437',
    messagingSenderId: '1019816135958',
    projectId: 'tgwapp-75d8b',
    storageBucket: 'tgwapp-75d8b.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-OYkuS2RDiQuPGFXrcvIWIRuT4qkMbv8',
    appId: '1:1019816135958:ios:14d015525926a25f59d437',
    messagingSenderId: '1019816135958',
    projectId: 'tgwapp-75d8b',
    storageBucket: 'tgwapp-75d8b.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8l6Y7XnzTyNOs6S3OpsJ1DuAIa_2p7lg',
    appId: '1:1019816135958:web:ad8d2b252457a65e59d437',
    messagingSenderId: '1019816135958',
    projectId: 'tgwapp-75d8b',
    authDomain: 'tgwapp-75d8b.firebaseapp.com',
    storageBucket: 'tgwapp-75d8b.firebasestorage.app',
    measurementId: 'G-6YJNW7SG5M',
  );
}